spring:
  profiles:
    include: common
  mvc:
    view.prefix: /pages/
    view.suffix: .jsp

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %contextName [%thread] %-5level %logger{36} - %msg%n"
